### ISSUE TITLE
Can't decrypt any Amazon Kindle files

### ISSUE THREAD

**Issue by RealStickman** [noDRM/DeDRM_tools#38]
I can't decrypt any books anymore for some reason. It did work before. Not sure what exactly broke it.

# Environment
- Wine 7.1
- Kindle for PC 1.26.0
- Calibre 5.36.0
- DeDRM 10.0.2
- KFX Input 1.46.0

# What I tried
- Make sure plugins are up to date
- Remove and readd Kindle key in plugin options

# Logs
## AZW file (manga)
<details>
  <summary>Expand Log</summary>

```
QLayout::addChildLayout: layout "" already has a parent
Gather KFX-ZIP (from KFX Input) 1.46.0: Importing /home/marc/Downloads/Kindle/B07CTBBGZF_EBOK/B07CTBBGZF_EBOK.azw
Gather KFX-ZIP (from KFX Input): File is not KFX format
DeDRM v10.0.2: Trying to decrypt B07CTBBGZF_EBOK.azw
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Demon Slayer: Kimetsu no Yaiba, Vol. 1
Error getting PIDs from database default_key: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(map(bytes,getK4Pids(md1, md2, kDatabase)))
  File "calibre_plugins.dedrm.kgenpids", line 209, in getK4Pids
    kindleAccountToken = bytearray.fromhex((kindleDatabase[1])['kindle.account.tokens'])
TypeError: list indices must be integers or slices, not str
Found 0 keys to try after 0.2 seconds
Crypto Type is: 2
DeDRM v10.0.2: Failed to decrypt with error: No key found in 0 PIDs tried.
DeDRM v10.0.2: Looking for new default Kindle Key after 0.2 seconds
0d00:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0032F558
DeDRM v10.0.2: Python3 exec found as wine py.exe -3
DeDRM v10.0.2: Running kindlekey.py under Wine
kindlekey.py v3.0
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\marc\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\users\marc\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1603539353' and UserName 'marc'
Saved a key to D:\home\marc\.config\calibre\plugins\DeDRM\libraryfiles\winekeysdir\kindlekey1.k4i
0d20:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0032F558
DeDRM v10.0.2: Found and decrypted 1 key file
DeDRM v10.0.2: Found 1 new key
MobiDeDrm v1.0.
Copyright © 2008-2020 The Dark Reverser, Apprentice Harper et al.
Decrypting Kindle Format 8 ebook: Demon Slayer: Kimetsu no Yaiba, Vol. 1
Error getting PIDs from database default_key_2: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(map(bytes,getK4Pids(md1, md2, kDatabase)))
  File "calibre_plugins.dedrm.kgenpids", line 209, in getK4Pids
    kindleAccountToken = bytearray.fromhex((kindleDatabase[1])['kindle.account.tokens'])
TypeError: list indices must be integers or slices, not str
Found 0 keys to try after 4.7 seconds
Crypto Type is: 2
DeDRM v10.0.2: Ultimately failed to decrypt after 4.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.mobidedrm", line 500, in processBook
    raise DrmException("No key found in {0:d} PIDs tried.".format(len(goodpids)))
calibre_plugins.dedrm.mobidedrm.DrmException: No key found in 0 PIDs tried.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 4.7 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
```
</details>

## KFX file (ebook)
<details>
  <summary>Expand Log</summary>

```
QLayout::addChildLayout: layout "" already has a parent
Gather KFX-ZIP (from KFX Input) 1.46.0: Importing /home/marc/Downloads/Kindle/B07HF4PSDQ_EBOK/B07HF4PSDQ_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 6 file(s) as /tmp/calibre_5.36.0_tmp__uowar79/qc35d8va.kfx-zip
DeDRM v10.0.2: Trying to decrypt qc35d8va.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: qc35d8va
Error getting PIDs from database default_key: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(map(bytes,getK4Pids(md1, md2, kDatabase)))
  File "calibre_plugins.dedrm.kgenpids", line 209, in getK4Pids
    kindleAccountToken = bytearray.fromhex((kindleDatabase[1])['kindle.account.tokens'])
TypeError: list indices must be integers or slices, not str
Found 0 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5da5ce61-ee06-410e-9343-13229b0aad5c.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/tmp/calibre_5.36.0_tmp__uowar79/puw1uq_jplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/tmp/calibre_5.36.0_tmp__uowar79/puw1uq_jplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/tmp/calibre_5.36.0_tmp__uowar79/puw1uq_jplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v10.0.2: Failed to decrypt with error: Failed to decrypt KFX DRM voucher with any key
DeDRM v10.0.2: Looking for new default Kindle Key after 0.1 seconds
091c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0032F558
DeDRM v10.0.2: Python3 exec found as wine py.exe -3
DeDRM v10.0.2: Running kindlekey.py under Wine
kindlekey.py v3.0
Copyright © 2010-2020 by some_updates, Apprentice Harper et al.
searching for kinfoFiles in C:\users\marc\AppData\Local
Found K4PC 1.25+ kinf2018 file: C:\users\marc\AppData\Local\Amazon\Kindle\storage\.kinf2018
Decrypted key file using IDString '1603539353' and UserName 'marc'
Saved a key to D:\home\marc\.config\calibre\plugins\DeDRM\libraryfiles\winekeysdir\kindlekey1.k4i
093c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFA, 0032F558
DeDRM v10.0.2: Found and decrypted 1 key file
DeDRM v10.0.2: Found 1 new key
Decrypting KFX-ZIP ebook: qc35d8va
Error getting PIDs from database default_key_2: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(map(bytes,getK4Pids(md1, md2, kDatabase)))
  File "calibre_plugins.dedrm.kgenpids", line 209, in getK4Pids
    kindleAccountToken = bytearray.fromhex((kindleDatabase[1])['kindle.account.tokens'])
TypeError: list indices must be integers or slices, not str
Found 0 keys to try after 4.6 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.5da5ce61-ee06-410e-9343-13229b0aad5c.voucher
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.dedrm.kfxdedrm", line 83, in decrypt_voucher
    voucher.decryptvoucher()
  File "/tmp/calibre_5.36.0_tmp__uowar79/puw1uq_jplugin_unzip/ion.py", line 879, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/tmp/calibre_5.36.0_tmp__uowar79/puw1uq_jplugin_unzip/ion.py", line 758, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/tmp/calibre_5.36.0_tmp__uowar79/puw1uq_jplugin_unzip/ion.py", line 98, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
DeDRM v10.0.2: Ultimately failed to decrypt after 4.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Running file type plugin DeDRM failed with traceback:
Traceback (most recent call last):
  File "calibre_plugins.dedrm.__init__", line 795, in KindleMobiDecrypt
    book = k4mobidedrm.GetDecryptedBook(path_to_ebook,kindleDatabases,androidFiles,serials,pids,self.starttime)
  File "calibre_plugins.dedrm.k4mobidedrm", line 244, in GetDecryptedBook
    mb.processBook(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 45, in processBook
    self.decrypt_voucher(totalpids)
  File "calibre_plugins.dedrm.kfxdedrm", line 89, in decrypt_voucher
    raise Exception("Failed to decrypt KFX DRM voucher with any key")
Exception: Failed to decrypt KFX DRM voucher with any key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.dedrm.__init__", line 888, in run
    decrypted_ebook = self.KindleMobiDecrypt(path_to_ebook)
  File "calibre_plugins.dedrm.__init__", line 838, in KindleMobiDecrypt
    raise DeDRMError("{0} v{1}: Ultimately failed to decrypt after {2:.1f} seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md".format(PLUGIN_NAME, PLUGIN_VERSION,time.time()-self.starttime))
calibre_plugins.dedrm.DeDRMError: DeDRM v10.0.2: Ultimately failed to decrypt after 4.6 seconds. Read the FAQs at Harper's repository: https://github.com/apprenticeharper/DeDRM_tools/blob/master/FAQs.md
Package KFX (from KFX Input) 1.46.0: Packaging /tmp/calibre_5.36.0_tmp__uowar79/qc35d8va.kfx-zip
Processing container: B07HF4PSDQ_EBOK.azw
Running file type plugin Package KFX (from KFX Input) failed with traceback:
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/customize/ui.py", line 175, in _run_filetype_plugins
    nfp = plugin.run(nfp) or nfp
  File "calibre_plugins.kfx_input.package_filetype", line 21, in run
    return self.run_kfx(path_to_ebook)
  File "calibre_plugins.kfx_input.package_filetype", line 32, in run_kfx
    kfx_data = YJ_Book(path_to_ebook).convert_to_single_kfx()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 84, in convert_to_single_kfx
    self.decode_book()
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 211, in decode_book
    container = self.get_container(datafile)
  File "calibre_plugins.kfx_input.kfxlib.yj_book", line 318, in get_container
    raise KFXDRMError("Book container %s has DRM and cannot be converted" % datafile.name)
calibre_plugins.kfx_input.kfxlib.utilities.KFXDRMError: Book container B07HF4PSDQ_EBOK.azw has DRM and cannot be converted
KFX metadata reader (from KFX Input) activated for /tmp/calibre_5.36.0_tmp__uowar79/suqbiixq_add_books/0/B07HF4PSDQ_EBOK.kfx-zip
```
</details>

**Comment by tsmithe** [comment]
I am suffering from this too. The key error seems to be the following:
```
Traceback (most recent call last):
  File "calibre_plugins.dedrm.kgenpids", line 299, in getPidList
    pidlst.extend(map(bytes,getK4Pids(md1, md2, kDatabase)))
  File "calibre_plugins.dedrm.kgenpids", line 209, in getK4Pids
    kindleAccountToken = bytearray.fromhex((kindleDatabase[1])['kindle.account.tokens'])
TypeError: list indices must be integers or slices, not str
```

**Comment by ElleKayEm** [comment]
For either format, was the book downloaded with the currently installed Kindle for PC?

For KFX format, you're sure the book was downloaded with no later then Kindle for PC version 1.26?

**Comment by tsmithe** [comment]
In my case, the book was downloaded with the currently installed Kindle for PC, and I downloaded it in AZW format.

**Comment by ElleKayEm** [comment]
All books downloaded with Kindle for PC have the AZW extension regardless of underlying format.  Unless you have KFX downloads disabled, that's likely what you'll get.

**Comment by RealStickman** [comment]
> For either format, was the book downloaded with the currently installed Kindle for PC?
> 
> For KFX format, you're sure the book was downloaded with no later then Kindle for PC version 1.26?

Yes, I used Kindle for PC 1.26

**Comment by j-howell** [comment]
> Error getting PIDs from database default_key: list indices must be integers or slices, not str

This error is caused by a bug in DeDRM that prevents it from obtaining the Kindle for PC key when running under Linux/Wine.

The bug was introduced when the function WineGetKeys was changed to return a pair of values (Add UUID to adobekey DER file names, Nov 15, 2021), but only three of the six calls to this function were updated to expect that.

**Comment by noDRM** [comment]
> This error is caused by a bug in DeDRM that prevents it from obtaining the Kindle for PC key when running under Linux/Wine.

Damnit. I'm going to try and fix this soon-ish. Thanks for the detailed description of the cause of the bug.

**Comment by noDRM** [comment]
> This error is caused by a bug in DeDRM that prevents it from obtaining the Kindle for PC key when running under Linux/Wine.

This should now been fixed in bb170688ba67557de2400f377ab907b991437b30, but I currently don't have a working K4PC setup to verify that myself.

**Comment by RealStickman** [comment]
Can I use `make_release.py` on the master branch to check whether this is working?  
Or do I need different build steps?

**Comment by noDRM** [comment]
Yes, you can do that. Checkout the master branch, then run `make_release.py`, then you'll get a "DeDRM_tools.zip" file which will contain the Calibre plugin ZIP file.

**Comment by j-howell** [comment]
I am reluctant to contribute changes to this project due to DMCA concerns, but I will mention here that the bug that causes issue #30 (Corrupted output for decrypted AZW) is still present in mobidedrm.py. It compares a byte string against '%MOP' instead of b'%MOP' in two places.

**Comment by noDRM** [comment]
Thanks, I seem to have missed that because the issue was already closed. Should be fixed with 2d51005cf141d267fc4b278f742d319e1515a17d.

**Comment by j-howell** [comment]
> Thanks, I seem to have missed that because the issue was already closed. Should be fixed with [2d51005](https://github.com/noDRM/DeDRM_tools/commit/2d51005cf141d267fc4b278f742d319e1515a17d).

Thank you.

**Comment by RealStickman** [comment]
Sorry for the late reply, I only now had the time to try it out.  
Both conversions work now.  

There's still one error with KFX files, but the program succeeds using a different method presumably.  

<details>
  <summary>Expand Log</summary>

```
Gather KFX-ZIP (from KFX Input) 1.47.0: Importing /home/marc/Downloads/Kindle/B00SN93AHU_EBOK/B00SN93AHU_EBOK.azw
Gather KFX-ZIP (from KFX Input): Gathered 4 file(s) as /tmp/calibre_5.39.1_tmp_mkt57won/wjjegqrv.kfx-zip
DeDRM v10.0.2: Trying to decrypt wjjegqrv.kfx-zip
Using Library AlfCrypto DLL/DYLIB/SO
Decrypting KFX-ZIP ebook: wjjegqrv
Got DSN key from database default_key_1648538642
Found 1 keys to try after 0.1 seconds
Decrypting KFX DRM voucher: amzn1.drm-voucher.v1.9165865c-183e-48ee-be9f-6dd069311856.voucher
Traceback (most recent call last):
  File "/home/marc/.config/calibre/plugins/DeDRM.zip/kfxdedrm.py", line 105, in decrypt_voucher
    voucher.decryptvoucher()
  File "/home/marc/.config/calibre/plugins/DeDRM.zip/ion.py", line 886, in decryptvoucher
    b = pkcs7unpad(b, 16)
  File "/home/marc/.config/calibre/plugins/DeDRM.zip/ion.py", line 762, in pkcs7unpad
    _assert(paddinglen > 0 and paddinglen <= blocklen, "Incorrect padding - Wrong key")
  File "/home/marc/.config/calibre/plugins/DeDRM.zip/ion.py", line 102, in _assert
    raise Exception(msg)
Exception: Incorrect padding - Wrong key
KFX DRM voucher successfully decrypted
Decrypting KFX DRMION: B00SN93AHU_EBOK.azw
Decryption succeeded after 0.2 seconds
DeDRM v10.0.2: Finished after 0.2 seconds
Package KFX (from KFX Input) 1.47.0: Packaging /tmp/calibre_5.39.1_tmp_mkt57won/f1lydc_2.kfx-zip
Processing container: B00SN93AHU_EBOK.azw
Processing container: CR!2DY3WW3JNX3M7DNA213RHZZM2C9W.azw.res
Processing container: CR!YYXC6MAZJ11W1CF0SMMN45A51FH1.azw.md
kfxgen version: 20.12.238.0
Features: CanonicalFormat-2, kfxgen.textBlock-1, max_id-787, reflow-style-2, yj_table-1
Metadata: ASIN=B00SN93AHU, asset_id=CR!4SC60KQX4H0YN7C7HS5XZ8S173WQ, author="Tchaikovsky, Adrian", book_id=N_iEhTliQ_qMHZAbIN78uA0, cde_content_type=EBOK, content_id=B00SN93AHU, cover_image=1056x1600, creator_version=2.15.0, file_creator=YJConversionTools, is_sample=False, issue_date=2015-06-04, language=en, nested_span=enabled, override_kindle_font=False, pages=610, publisher="Pan Macmillan", reading_orders=1, selection=enabled, title="Children of Time: Winner of the 2016 Arthur C. Clarke Award (The Children of Time Novels)"
Package KFX (from KFX Input): Imported as /tmp/calibre_5.39.1_tmp_mkt57won/fcml6cxr.kfx
KFX metadata reader (from KFX Input) activated for /tmp/calibre_5.39.1_tmp_mkt57won/s7hhfwof_add_books/0/B00SN93AHU_EBOK.kfx
```

</details>
